### ISSUE TITLE
Integrate into Can proper

### ISSUE THREAD

**Issue by andrejewski** [canjs/can-dom-mutate#19]
This issue articulates the changes and schedule to get `can-dom-mutate` integrated into CanJs.

#### Effected packages, ordered by what will be touched first:
- can-util
- [can-view-live](https://github.com/canjs/can-view-live/blob/7c48767ba1638eb11c0fd2047a354d5bac5ac7ff/lib/core.js#L56-L64)
- [can-stache-bindings](https://github.com/canjs/can-stache-bindings/blob/fe2a16fd321dc15d7f036682b380d7ecc88d66a7/can-stache-bindings.js#L292)
- can-simple-dom

#### 3.0 Schedule
| # | Task | Status |
|---|-------|-------|
| 0 | Update dependencies to use `can-dom-data` and `can-globals` | Done
| 1 | Replace the events in `can-util/dom/events/${inserted/removed/attributes}` and see CDM is a drop in replacement for can-util and full canjs; tweak to match existing behavior (potentially creating a one-off module in CDM to patch the differences)
| 2 | Repeat for can-view-live, making sure the `removed` event works as expected
| 3 | Repeat for can-stache-bindings (and this point if everything passes `can-simple-dom` should just work as well but we can run some tests perhaps)
| 4 | Publish the changes to the above modules in v3.0s.

#### 4.0 Schedule
| # | Task |
|---|-------|
| 0 | Update can-view-live and can-stache-bindings to use CDM directly instead of using DOM events

#### 4.0+ Schedule
| # | Task |
|---|-------|
| 0 | Alter can-view-live and can-view-list to leverage text node level observation

---

Let me know if I am missing any packages/pieces that will need to be addressed.

@justinbmeyer @matthewp @phillipskevin

**Comment by matthewp** [comment]
It would be good to describe how can-dom-mutate differs from the can-util API. I know that it's a *different* API, but how is it different? Given a couple of code examples of how something was used in can-util and how they would now be used with can-dom-mutate would help me to understand the difference.

**Comment by andrejewski** [comment]
@matthewp For 3.x, the can-util API would not change by adopting CDM under the hood. For 4.x, can-util/dom/events would hopefully be replaced with can-dom-events. In either case, the way you add these listeners stays the same (because the events support both can-util and can-dom-events styles via the [compat](https://github.com/canjs/can-dom-mutate/blob/master/events/compat.js)).

The potential breakage would removing them from can-util outright.

**Comment by matthewp** [comment]
Can you still give some code examples? Assume I don't know what the can-util/dom/events api is (I only have a vague memory of it, tbh).

**Comment by andrejewski** [comment]
```js
import canEvents from 'can-util/dom/events'

var myDomNode
canEvents.addEventListener.call(myDomNode, 'removed', function () {})
```

Nothing changes and it 4.0 it *could* be completed removed.

**Comment by justinbmeyer** [comment]
Benefits:

- Improved performance:
  - We won't have to dispatch and register DOM custom event dispatching.  
  - It's likely we can avoid wrapping functions like `domMutate.appendChild`
- Avoid warnings (and potential errors) with code like: `<input value:bind="value"/>`
- Ability to fix memory leaks with bindings like `stache("{{foo}}")` as we will be able to listen to text nodes being removed from the dom.

Risks:
- In 4.0 - breaking APIs from 3.0, but with easily to swap packages.  For example, instead of `require("can-util/dom/events/inserted")`, users will import `can-dom-mutate/blob/master/events/inserted`.

**Comment by matthewp** [comment]
I think this is fine to proceed with 👍

**Comment by andrejewski** [comment]
3.x Changes:
- Merge PRs for mutation timing issues
  - [Merge `can-view-live` PR](https://github.com/canjs/can-view-live/pull/71) and patch release
  - [Merge `can-ejs` PR](https://github.com/canjs/can-ejs/pull/51) and patch release
  - [Merge `can-stache-bindings` PR](https://github.com/canjs/can-stache-bindings/pull/341) and patch release
- [Merge `can-dom-mutate` PR](https://github.com/canjs/can-dom-mutate/pull/23) and release v0.2 or v1.0
- [Merge `can-util` PR](https://github.com/canjs/can-util/pull/384) and patch/minor release
- Update `canjs/canjs` with all updated version and patch release

**Comment by andrejewski** [comment]
4.0 Steps:
1.  remove can-dom-data from can-dom-mutate
2. make a can-dom-data 4.X that uses can-dom-mutate to clean itself up
3. remove the can-dom-data stuff from inserted & removed
4. using can-dom-mutate everywhere we can
5. pointing 4.X stuff to 4.X can-dom-data
6. can-event-dom-inserted & can-event-dom-removed

**Comment by andrejewski** [comment]
Looking at the current trace data for can@major, I see the following packages dependent on can-util/dom/mutate, can-util/events, can-util/events/{mutation}, and can-util/dom/data and can-dom-data-state:

```
can-control
can-connect
can-component
can-event-queue
can-event-dom-enter
can-event-dom-radiochange
can-stache
can-stache-bindings
can-view-live
can-view-import
can-view-model
can-view-callbacks
can-view-nodelist
can-view-target
```

I will work on branches off of respective major branches with the branch name `magneto`.

**Comment by justinbmeyer** [comment]
Here's my order:

```js
can-event-queue
can-view-nodelist
can-view-target
can-view-callbacks
can-event-dom-enter
can-event-dom-radiochange
can-view-model
can-view-live
can-control
can-stache
can-stache-bindings
can-component
can-view-import
can-connect
```

**Comment by andrejewski** [comment]
The track list:
- [`can-event-queue`](https://github.com/canjs/can-event-queue/tree/magneto)
- [`can-view-nodelist`](https://github.com/canjs/can-view-nodelist/tree/magneto)
- [`can-view-target`](https://github.com/canjs/can-view-target/tree/magneto)
